<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE software[
<!--Definicion de elementos-->
<!ELEMENT software (programa+)>
<!ELEMENT programa (titulo,(espa単ol|ingles),precio,categoria,descripcion,departamentos,web?,caratula?)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT ingles EMPTY>
<!ELEMENT espa単ol EMPTY>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT categoria (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT departamentos (departamento+)>
<!ELEMENT departamento (#PCDATA)>
<!ELEMENT web (#PCDATA)>
<!ELEMENT caratula (#PCDATA)>
<!ATTLIST programa codigo CDATA #REQUIRED>
<!ATTLIST programa version ID #REQUIRED>
<!ATTLIST programa a単o CDATA #IMPLIED>
<!ATTLIST programa sistema_operativo (windows|mac) "windows">
]>

<software>
    <programa codigo="codigo" version="w3" sistema_operativo="windows">
        <titulo>contasoft</titulo>
        <espa単ol/>
        <precio>38 euros</precio>
        <categoria>contabilidad</categoria>
        <descripcion>programa de contabilidad</descripcion>
        <departamentos>
            <departamento>departamento de informatica</departamento>
        </departamentos>
        <web>https://web.contasoft.com</web>
        <caratula>caratula de contasoft</caratula>
    </programa>
</software>