<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE listaclientes [
    <!ELEMENT listaclientes (cliente+)>
    <!ELEMENT cliente (nombre, diasentrega+)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT diasentrega (#PCDATA)>
    <!ATTLIST cliente cif CDATA #REQUIRED>
]>

<listaclientes>
    <cliente cif="567743">
        <nombre>Mercasa</nombre>
        <diasentrega>Lunes</diasentrega>
        <diasentrega>Martes</diasentrega>
    </cliente>

    <cliente cif="515524">
        <nombre>Acer SL</nombre>
        <diasentrega>Lunes</diasentrega>
    </cliente>
    
    
</listaclientes>