=== A-Algaba/1DAM_LMSGI_Alberto/TEMA11/caso_practico_1/ordenadores.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="ordenadores">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ordenador" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="marca" type="xs:string"></xs:element>
                            <xs:element  name="procesador" type="xs:string"></xs:element>
                            <xs:element name="ram" type="xs:string"></xs:element>
                            <xs:element name="discoduro" type="tipodisco"></xs:element>
                            <xs:element name="puertosconexion" type="xs:unsignedShort"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="tipo" type="xs:string" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="tipodisco">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ssd"></xs:enumeration>
            <xs:enumeration value="hdd"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== A-Algaba/1DAM_LMSGI_Alberto/TEMA11/caso_practico_1/ordenadores.xml
<?xml version="1.0" encoding="UTF-8"?>

<ordenadores xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ordenadores.xsd">

    <ordenador tipo = "sobremesa">
        <marca>MSI</marca>
        <procesador>amd</procesador>
        <ram>32</ram>
        <discoduro>ssd</discoduro>
        <puertosconexion>10</puertosconexion>
    </ordenador>

    <ordenador tipo="portatil">
        <marca>Asus</marca>
        <procesador>intel</procesador>
        <ram>16</ram>
        <discoduro>hdd</discoduro>
        <puertosconexion>4</puertosconexion>
    </ordenador>

</ordenadores>
