=== A-Algaba/1DAM_LMSGI_Alberto/TEMA11/ejemplo5/concesionario.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="concesionario">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="coche" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="marca" type="xs:string"></xs:element>
                            <xs:element name="modelo" type="xs:string"></xs:element>
                            
                            <xs:choice>
                                <xs:element name="cilindrada" type="xs:decimal"></xs:element>
                                <xs:element name="caballos" type="tipocaballos" maxOccurs="unbounded"></xs:element>
                            </xs:choice>

                            <xs:element name="combustible" type="tipocombustible"></xs:element>
                            <xs:element name="precio" type="xs:string"></xs:element>
                            <xs:element name="a単o" type="tipoa単o" minOccurs="0"></xs:element>
                            <xs:element name="color" type="xs:string"></xs:element>
                            <xs:element name="interesado" type="xs:string" maxOccurs="unbounded" minOccurs="0"></xs:element>
                            <xs:element name="accesorios" type="tresaccesorios" minOccurs="0"></xs:element>

                        </xs:sequence>
                        <xs:attribute name="matricula" type="xs:string" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="provincia" type="xs:string"></xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="tipocombustible">
        <xs:restriction base="xs:string">
            <xs:enumeration value="diesel"></xs:enumeration>
            <xs:enumeration value="gasolina"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipocaballos">
        <xs:restriction base="xs:unsignedShort">
            <xs:minInclusive value="60"></xs:minInclusive>
            <xs:maxInclusive value="220"></xs:maxInclusive>
        </xs:restriction>
    </xs:simpleType>

    <!-- a単o de 4 cifras-->
    <xs:simpleType name="tipoa単o">
        <xs:restriction base="xs:unsignedShort">
            <xs:totalDigits value="4"></xs:totalDigits>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipodni">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{8}[A-Z]"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoaccesorio">
        <xs:list itemType="xs:string"></xs:list>
    </xs:simpleType>

    <xs:simpleType name="tresaccesorios">
        <xs:restriction base="tipoaccesorio">
            <xs:maxLength value="3"></xs:maxLength>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== A-Algaba/1DAM_LMSGI_Alberto/TEMA11/ejemplo3/concesionario.xml
<?xml version="1.0" encoding="UTF-8"?>

<concesionario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="concesionario.xsd" provincia="Malaga">

    <coche matricula="6732KPC">
        <marca>Seat</marca>
        <modelo>Ateca</modelo>
        <cilindrada>1.7</cilindrada>
        <combustible>diesel</combustible>
        <precio>23.000€</precio>
        <año>2018</año>
        <color>negro</color>
        <interesado>33358678A</interesado>
        <interesado>35704221K</interesado>
    </coche>

    <coche matricula="8834GHC">
        <marca>honda</marca>
        <modelo>civic</modelo>
        <cilindrada>1.2</cilindrada>
        <combustible>Gasolina</combustible>
        <precio>5.000€</precio>
        <color>rojo</color>
        <interesado>99887723T</interesado>
    </coche>

    <coche matricula="6743FJK">
        <marca>renault</marca>
        <modelo>megane</modelo>
        <caballos>120</caballos>
        <combustible>Diesel</combustible>
        <precio>7.000€</precio>
        <color>azul</color>
    </coche>

</concesionario>
